apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics
  namespace: monitoring
  labels:
    app: victoria-metrics
spec:
  selector:
    app: victoria-metrics
  type: ClusterIP
  ports:
  - port: 8428
    targetPort: 8428
    protocol: TCP
    name: http
