apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'ksadokk@gmail.com'
      smtp_auth_username: 'ksadokk@gmail.com'
      smtp_auth_password: 'pqusqvpzsdvwrdcy'
      smtp_require_tls: true

    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'gmail-notifications'
      routes:
      - match:
          severity: critical
        receiver: 'critical'
      - match:
          severity: warning
        receiver: 'warning'

    receivers:
    - name: 'gmail-notifications'
      email_configs:
      - to: 'ksadokk@gmail.com'
        send_resolved: true
    - name: 'critical'
      email_configs:
      - to: 'ksadokk@gmail.com'
        send_resolved: true
    - name: 'warning'
      email_configs:
      - to: 'ksadokk@gmail.com'
        send_resolved: true
