apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: VictoriaMetrics
      type: prometheus
      access: proxy
      url: http://victoria-metrics:8428
      isDefault: true
      editable: true
      jsonData:
        timeInterval: 30s
        manageAlerts: true
        alertmanagerUid: alertmanager
        prometheusType: Prometheus
        prometheusVersion: "2.40.0"



    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100


    - name: Alertmanager
      type: alertmanager
      access: proxy
      url: http://alertmanager:9093
      jsonData:
        implementation: prometheus



    - name: VMAlert
      type: prometheus
      uid: vmalert
      access: proxy
      url: http://vmalert:8880
      editable: true

