{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "grafana-admin-creds",
    "namespace": "monitoring",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "grafana-admin-creds",
        "namespace": "monitoring",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "admin-password": "AgDhBnslPBn5mLVeZOLnqSSjVZR5crAeAkq6F+sVw7AKwcy3DQOVL3hekOYmmIEoDdZf4DwGxrWG6nKt5yIkoOQVhG01ffDPKfhYJtrJZyL7F8XkTN1ItM9k8uextpCaslOd5lJHva04+crODl+jASfHmHiWC1NEJbnwUhQidrIumBRGIwJzHm/2H8U/Vn1xdLqgfy/edInIQiE3Umr4f2GX4pWscXAw3E/riVoGMIgcoaQ4jjyAIp58FEj32N/dl5+AY+wJLGnbCfKLoUD2kBLACtLGuvj5I3sl1GpwJBQujRCTETjqN8JtczuePk1uSKteTtTyoO6nS+rWR18wFscwUb7mUu6eGOI7Onx7kGdMmfm/wvu94fH33vQhNqHXXyw2U7cxh6eDTx0ybTdc+m9q4YuC7IJGaLQuGIezuvbPYJ4RXUdxpEuKTfl10tbIPMWaVeRrKGVMRbyNpAPT25joAuvpCmtxHCBVj4ahlEPu/zyvMW3Y1KU2lmqJRPjlS6F7K31y+1/QMlNYMfr9NXB+Jt5bmkGMsRuF8oHEweD5J7rjfvU4BazSHMmInOKPxwRwSpP/HmPmJb46a/qKClJ+rEwXs6OkvKZRG1m44X9nKYCNNKJU5gUiQ6xl6d+5xJOn4ZQIrYbKGHu46BAvaovfJkLGWntkWoMtA2AcMpTNdcz/fetmhjSqYFqXu5y6HjHYVNlUOA==",
      "admin-user": "AgC5wefW4iDzqCKDGbiBWJUYEC1mt8nd/43P6YljUPI7diyVWVM6n8Vb4IA4mzbgpoZAa8J2QFC54nRQz4ElmcvDPjxlEmrNfrjFO78krIBpAp1ssuow2ZvSa823/UrGPN4J0C5PH0r+nfqGXxSOcddrXzvysbgab+RzQ7uoKRj2lvGhQ9tiu35NfYNYAGeFX4LlSDsaItYyWJ/B/vYDPWzcTcSG6KIa9nkpLvwDqux+08FcL6oWekRuEV9HZMmrfDsCqelJd87CRw8gXtgPd8GriEb16qrwAEkpbtrN/4wO19lytEK3MqFlA7fIhciVD0B1QkKW3d+udtYOeP0ZJCiFa7OOpHKlOcxTlrrimaniCU71pt7oLDQDwZkdyZnciDX/jLlt+q5DXD4sgJeCO04Hp6v6cQ5npyC5TGK8xPFoOjkGVH6X5PFElzRlvyVTvIzrJULDY02UCwbu1zeQ3Rulm+CydCGuaXSYMREWN3F35xM29UGOKiAlly8crsmt6SEuk8hqftI2OVl+qLNwpb/muiKdoWDnhrv4BgJN2K6+A5uJWAidlCDyBkL9Wlmhhj3wZfTbth00UVBv/Q/U7ly8iAG03DnvWpXyW/U5LK5+KBAboRdkETaYMXBo9jIrJ5eknm7kMMFMB7Tf2tdCkMG9KQYHCxGZr4dYtIqooLUFesUaavvGZtOTEeCiKc/fDf7XmrgdZQ=="
    }
  }
}
