[loadbalancer]
k3s-lb ansible_host=192.168.122.100 ansible_user=ubuntu

[k3s_bootstrap]
k3s-master-0 ansible_host=192.168.122.10 ansible_user=ubuntu

[masters]
k3s-master-1 ansible_host=192.168.122.11 ansible_user=ubuntu
k3s-master-2 ansible_host=192.168.122.12 ansible_user=ubuntu

[workers]
k3s-worker-0 ansible_host=192.168.122.20 ansible_user=ubuntu
k3s-worker-1 ansible_host=192.168.122.21 ansible_user=ubuntu

[k3s_cluster:children]
k3s_bootstrap
masters
workers

[all:vars]
ansible_ssh_private_key_file=~/.ssh/k3s_lab_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
k3s_version=v1.28.5+k3s1
