apiVersion: v1
kind: Service
metadata:
  name: vmalert
  namespace: monitoring
  labels:
    app: vmalert
spec:
  ports:
  - port: 8880
    targetPort: 8880
    name: http
  selector:
    app: vmalert
