apiVersion: v1
kind: Service
metadata:
  name: vmalert
  namespace: monitoring
  labels:
    app: vmalert
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8880"
spec:
  ports:
  - port: 8880
    targetPort: 8880
    name: http
  selector:
    app: vmalert
